project_name: phctl

before:
  hooks:
    # - go mod tidy
    # - go generate ./...
    #
release:
  prerelease: "false"
  extra_files:
    - glob: config/release/*.yaml

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source_code"

builds:
  - id: default
    main: ./cmd/phctl
    binary: phctl
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7

archives:
  - id: default
    builds:
      - default
    name_template: "phctl_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*

brews:
- tap:
    owner: phoban01
    name: homebrew-tap
  commit_author:
    name: phoban01
    email: phoban01@gmail.com
  folder: Formula
  homepage: https://example.com
  install: |
    bin.install "phctl"

checksum:
  name_template: "phctl_checksums.txt"
  extra_files:
    - glob: config/release/*.yaml
